#!/bin/bash
##################################################################################################
# '''
# // @Project      Install all of the dot files instead manually install every file (Simple)
# // @Author       Saccharide
# '''
##################################################################################################

sudo apt install build-essential cmake python3-dev
# Check if vimrc and bashrc exists, and make backup of them before override
if [ -f $HOME/.vimrc ]; then
    echo "----------------------"
    echo "Backing up vimrc ..."
    echo "----------------------"
    mv $HOME/.vimrc $HOME/.vimrc_backup
    echo "----------------------"
    echo "DONE"
    echo "----------------------"
fi
if [ -d $HOME/.vim ]; then
    echo "----------------------"
    echo "Backing up .vim ..."
    echo "----------------------"
    mv $HOME/.vim $HOME/.vim_backup
    echo "----------------------"
    echo "DONE"
    echo "----------------------"
fi
cp .vimrc $HOME
cp -R .vim $HOME
echo "[+] Creating .vimtmp for persistent undo..."
mkdir $HOME/.vimtmp
mv $HOME/.vim/bundle_temp $HOME/.vim/bundle

# Installing YouCompleteMe
cd ~/.vim/bundle/YouCompleteMe
./install.py --clang-complete

echo "[+] Adding saccharide.vim to colorscheme directory"
cp saccharide.vim ~/.vim/colors/
echo "Adding vim airline and clock"
cd $HOME/.vim/bundle
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/enricobacis/vim-airline-clock

echo "Adding vim easymotion"
# CHECK OUT VIM EASYMOTION, very cool, need to learn it sometimes
git clone https://github.com/easymotion/vim-easymotion

echo "Adding python syntax highlighting for vim"
git clone https://github.com/vim-python/python-syntax

echo "Installing black"
pip install black
mkdir -p ~/.vim/pack/python/start/black/plugin
mkdir -p ~/.vim/pack/python/start/black/autoload
curl https://raw.githubusercontent.com/psf/black/stable/plugin/black.vim -o ~/.vim/pack/python/start/black/plugin/black.vim
curl https://raw.githubusercontent.com/psf/black/stable/autoload/black.vim -o ~/.vim/pack/python/start/black/autoload/black.vim

echo "[+] Success."
