#!/bin/bash
##################################################################################################
# '''
# // @Project      Install all of the dot files instead manually install every file (Simple)
# // @Author       Saccharide
# '''
##################################################################################################

sudo apt install build-essential cmake python3-dev
# Check if vimrc and bashrc exists, and make backup of them before override
if [ -f $HOME/.vimrc ]; then
    echo "----------------------"
    echo "Backing up vimrc ..."
    echo "----------------------"
    mv $HOME/.vimrc $HOME/vimrc_backup
    echo "----------------------"
    echo "DONE"
    echo "----------------------"
fi
if [ -d $HOME/.vim ]; then
    echo "----------------------"
    echo "Backing up .vim ..."
    echo "----------------------"
    mv $HOME/.vim $HOME/vim_backup
    echo "----------------------"
    echo "DONE"
    echo "----------------------"
fi
cp .vimrc $HOME
cp -R .vim $HOME
mv $HOME/.vim/bundle_temp $HOME/.vim/bundle

# Installing YouCompleteMe
cd ~/.vim/bundle/YouCompleteMe
./install.py --clang-complete
